/* **************************************************************************************
* ? 2013 Enrollment Rx, LLC. All Rights Reserved
*
* Public class: CampusConstant
  Use within campus package to log errors 
*  
* Created by Arpit Sharma, Enrollmentrx: Feb/10/2015
*
*****************************************************************************************/
public with sharing class PortalPackageException Extends Exception{

}